#*** There are 3 different ways to assign variables a value...

# single variable assignment...
varName1 = 10

# multiple variables assignment/(assigning the same value to each separate variable)...
varName2 = varName3 = 50

# multiple variables assignment/(assigning different values to each separate variable)...
varName4, varName5 = 44,55

# printout variable values...
print(varName1,varName2,varName3,varName4,varName5)

# prints out... 
# 10,50,50,44,55

